# HTTP

server {
    listen 80;
    # 可选，有IPv6可开启
    # listen [::]:80;
    # 域名
    server_name pv-tool-agpl.com;

    # 网站根目录路径
    root /var/www/pv-tool-agpl;
    index index.html;
    
    location / {
        try_files $uri $uri/ =404;
    }
}

# HTTPS

server {
    listen 443;
    # 可选，有IPv6可开启
    # listen [::]:443;
    # 域名
    server_name pv-tool-agpl.com;

    # TLS证书路径
    ssl_certificate /var/www/ssl/pv-tool-agpl.com/crt.crt;
    # TLS证书密钥路径
    ssl_certificate_key /var/www/ssl/pv-tool-agpl.com/key.pem;
    # TLS版本
    ssl_protocols TLSv1.2 TLSv1.3;
    # 加密套件
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
    # 强制使用服务端定义的顺序（防止客户端使用弱加密套件）
    ssl_prefer_server_ciphers on;
    # 开启HTTP2
    http2 on;

    # 网站根目录路径
    root /var/www/pv-tool-agpl;
    index index.html;
    
    location / {
        try_files $uri $uri/ =404;
    }
}